### ISSUE TITLE
Editing the layout templates

### ISSUE THREAD

**Issue by pauloneillft** [Financial-Times/ui-style-guide#2]
@triblondon 
How do I do this?

I see a _layouts folder and a scss file. I assume there's some automation to getting the layouts to work. 

I want to make some tweaks, so how I do this. Also, I want to use something similar to the registry page. How do I get that template or any other ones.

**Comment by kaelig** [comment]
Paul is now fluent in Jekyll, Markdown, HTML and CSS so I think we can close this.
